-- Equivalente a database/migrations/1761885935168_create_users_table.ts (Lucid).
-- No incluye auth_access_tokens: la auth aquí es JWT stateless, no hay
-- tabla de tokens que persistir (ver JwtService).
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255),
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE
);
